export * from './compliments/compliments.component';
export * from './login/login.component';
export * from './not-found/not-found.component';
export * from './note/note.component';
export * from './home/home.component'
export * from './faq/faq.component'
export * from './register/register.component'
export * from './reset-password/reset-password.component';
export * from './gallery/gallery.component'
